config/routes.rb
Rails.application.routes.draw do

  resources :scan_header_tags
  resources :mime_types
  require 'sidekiq/web'

  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }
  mount Shrine.presign_endpoint(:cache) => "/qa_session_files/presign", as: 'presign_qa_session_files'

  mount Shrine.download_endpoint => "/files"

  resources :analysis_responses
  resources :analyses do
    resources :analysis_requests, shallow: true
  end
  resources :scan_protocols do
    resources :scan_protocol_matchers, shallow: true
    member do
      post :delete_specifications_file
      post :delete_analysis_options_file
    end
  end
  resources :sites do
    resources :scan_protocols, shallow: true
  end

  resources :analysis_requests do
    resources :analysis_responses, shallow: true
  end

  resources :qa_sessions do
    member do
      get :download_files
      post :match_scan_protocols
    end
    resources :qa_session_files, shallow: true
    resources :analysis_sessions, shallow: true
  end

  resources :phantom_module_files

  resources :equipment
  resources :accounts
  resources :reports

  resources :scan_series do
    member do
      get :download_files
    end
  end

  namespace :api, :defaults => { :format => :json } do
    namespace :v1 do
      resources :accounts, only: [:index, :show]
      resources :auth, only: [:create], controller: "authentication"
      resources :analysis_requests do
        resource :analysis_responses, shallow: true
      end
    end
  end

  root to: 'qa_sessions#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/analysis_request.rb
class AnalysisRequest < ApplicationRecord
  include Keyable

  # Relationships
  belongs_to :analysis_session
  belongs_to :scan_series
  has_one :analysis_response, dependent: :destroy

  def method_missing(method, *args)
    return analysis_response.send(method, *args) if analysis_response.respond_to?(method)
    return analysis_session.send(method, *args) if analysis_session.respond_to?(method)
    return scan_series.send(method, *args) if scan_series.respond_to?(method)
    super
  end

  # after_create :set_static_response_data
  after_create :set_initial_status

  scope :without_response, ->() { includes(:analysis_response).where(:analysis_responses => { :id => nil }) }

  def status
    "In progress"
  end

  def report_date
    qa_session.performed_at
  end

  def scan_acquisition_date
    scan_series.scan_acquisition_date
  end

  def performed_by
    "Bjarki"
  end

  # TODO: this bypasses the RabbitMQ workflow and should be removed
  def set_static_response_data
    create_analysis_response(response_data: JSON.parse(File.read(Rails.root.join('public', 'example.json'))))
  end

  def set_initial_status
    update(status: 'in progress')
  end
end

app/controllers/analysis_requests_controller.rb
class AnalysisRequestsController < ApplicationController
  before_action :set_analysis_request, only: [:show, :edit, :update, :destroy]

  # GET /analysis_requests
  # GET /analysis_requests.json
  def index
    @analysis_requests = AnalysisRequest.all
  end

  # GET /analysis_requests/1
  # GET /analysis_requests/1.json
  def show
  end

  # GET /analysis_requests/new
  def new
    @analysis_request = AnalysisRequest.new
  end

  # GET /analysis_requests/1/edit
  def edit
  end

  # POST /analysis_requests
  # POST /analysis_requests.json
  def create
    @analysis_request = AnalysisRequest.new(analysis_request_params)

    respond_to do |format|
      if @analysis_request.save
        format.html { redirect_to @analysis_request, notice: 'Analysis request was successfully created.' }
        format.json { render :show, status: :created, location: @analysis_request }
      else
        format.html { render :new }
        format.json { render json: @analysis_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /analysis_requests/1
  # PATCH/PUT /analysis_requests/1.json
  def update
    respond_to do |format|
      if @analysis_request.update(analysis_request_params)
        format.html { redirect_to @analysis_request, notice: 'Analysis request was successfully updated.' }
        format.json { render :show, status: :ok, location: @analysis_request }
      else
        format.html { render :edit }
        format.json { render json: @analysis_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /analysis_requests/1
  # DELETE /analysis_requests/1.json
  def destroy
    @analysis_request.destroy
    respond_to do |format|
      format.html { redirect_to analysis_requests_url, notice: 'Analysis request was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_analysis_request
      @analysis_request = AnalysisRequest.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def analysis_request_params
      params.require(:analysis_request).permit(:analysis_id, :scan_protocol_id)
    end
end

app/controllers/api/v1/analysis_requests_controller.rb
class Api::V1::AnalysisRequestsController < ApiController
  def index
    @analysis_requests = AnalysisRequest.without_response
  end

  def show
    @analysis_request = AnalysisRequest.friendly.find(params[:id])
  end
end

app/helpers/analysis_requests_helper.rb
module AnalysisRequestsHelper
end

app/views/analysis_requests/_analysis_requests.html.erb
<div class="table-responsive">
  <% analysis_requests.each do |req| %>
    <table class="table">
      <thead>
        <tr>
          <th>#</th>
          <th>File count</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><%= link_to req, req %></td>
          <td><%= req.qa_session_files.count %></td>
        </tr>
      </tbody>
    </table>
  <% end %>
</div>

app/views/analysis_requests/_form.html.erb
<%= form_with(model: analysis_request, local: true) do |form| %>
  <% if analysis_request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(analysis_request.errors.count, "error") %> prohibited this analysis_request from being saved:</h2>

      <ul>
      <% analysis_request.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :analysis_id %>
    <%= form.text_field :analysis_id, id: :analysis_request_analysis_id %>
  </div>

  <div class="field">
    <%= form.label :scan_protocol_id %>
    <%= form.text_field :scan_protocol_id, id: :analysis_request_scan_protocol_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/analysis_requests/edit.html.erb
<h1>Editing Analysis Request</h1>

<%= render 'form', analysis_request: @analysis_request %>

<%= link_to 'Show', @analysis_request %> |
<%= link_to 'Back', analysis_requests_path %>

app/views/analysis_requests/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Analysis Requests</h1>

<table class="table">
  <thead>
    <tr>
      <th>Analysis</th>
      <th>Scan Protocol</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @analysis_requests.each do |analysis_request| %>
      <tr>
        <td><%= analysis_request.analysis %></td>
        <td><%= analysis_request.scan_protocol %></td>
        <td><%= link_to 'Show', analysis_request %></td>
        <td><%= link_to 'Edit', edit_analysis_request_path(analysis_request) %></td>
        <td><%= link_to 'Destroy', analysis_request, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Analysis Request', new_analysis_request_path %>

app/views/analysis_requests/new.html.erb
<h1>New Analysis Request</h1>

<%= render 'form', analysis_request: @analysis_request %>

<%= link_to 'Back', analysis_requests_path %>

app/views/analysis_requests/show.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
  <div class="col-lg-8">
    <h2>
      <strong><%= @analysis_request.key %></strong>
      (<%= @analysis_request.created_at.to_date.to_s(:db) %>)
    </h2>
    <ol class="breadcrumb">
      <li>
        <%= link_to 'Analyses', analyses_path %>
      </li>
      <li>
        <%= link_to 'Analysis Requests', analysis_analysis_requests_path(@analysis_request.analysis) %>
      </li>
      <li class="active">
        <strong><%= @analysis_request %></strong>
      </li>
    </ol>
  </div>
  <div class="col-lg-4" class="page-heading-toolbox">
    <%= link_to 'View Report', report_path(@analysis_request.analysis), class: 'btn btn-primary btn-block btn-lg' %>
  </div>
</div>

<div class="wrapper wrapper-content">
  <div class="row">
    <div class="col-sm-12">
      <div class="ibox float-e-margins">
        <div class="ibox-title">
          <h5>Details</h5>
        </div>
        <div class="ibox-content">
          <dl class="dl-horizontal">
            <dt>File Count</dt>
            <dd><%= @analysis_request.qa_session_files.count %></dd>
            <dt>Request Data</dt>
            <dd><%= @analysis_request.request_data %></dd>
          </dl>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-12">
      <div class="ibox">
        <div class="ibox-title">
          <h5>Files</h5>
        </div>
        <div class="ibox-content">
          <% if @analysis_request.qa_session_files.count > 0 %>
          <%= render 'qa_session_files/qa_session_files', qa_session_files: @analysis_request.qa_session_files %>
          <% else %>
            <p>No files found.</p>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>