config/routes.rb
Rails.application.routes.draw do

  resources :scan_header_tags
  resources :mime_types
  require 'sidekiq/web'

  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }
  mount Shrine.presign_endpoint(:cache) => "/qa_session_files/presign", as: 'presign_qa_session_files'

  mount Shrine.download_endpoint => "/files"

  resources :analysis_responses
  resources :analyses do
    resources :analysis_requests, shallow: true
  end
  resources :scan_protocols do
    resources :scan_protocol_matchers, shallow: true
    member do
      post :delete_specifications_file
      post :delete_analysis_options_file
    end
  end
  resources :sites do
    resources :scan_protocols, shallow: true
  end

  resources :analysis_requests do
    resources :analysis_responses, shallow: true
  end

  resources :qa_sessions do
    member do
      get :download_files
      post :match_scan_protocols
    end
    resources :qa_session_files, shallow: true
    resources :analysis_sessions, shallow: true
  end

  resources :phantom_module_files

  resources :equipment
  resources :accounts
  resources :reports

  resources :scan_series do
    member do
      get :download_files
    end
  end

  namespace :api, :defaults => { :format => :json } do
    namespace :v1 do
      resources :accounts, only: [:index, :show]
      resources :auth, only: [:create], controller: "authentication"
      resources :analysis_requests do
        resource :analysis_responses, shallow: true
      end
    end
  end

  root to: 'qa_sessions#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/scan_protocol.rb
class ScanProtocol < ApplicationRecord
  include AnalysisOptionsFileUploader::Attachment.new(:analysis_options_file)
  include SpecificationsFileUploader::Attachment.new(:specifications_file)

  # Relationships
  belongs_to :site
  has_many :qa_session_files, dependent: :nullify
  has_many :matchers, class_name: "ScanProtocolMatcher", dependent: :destroy
  has_many :phantom_module_files, dependent: :destroy

  # Nested attributes
  accepts_nested_attributes_for :matchers,
                                allow_destroy: true,
                                reject_if: ->(att) { att['matcher'].blank? && att['value_type_matcher_id'].blank? }

  accepts_nested_attributes_for :phantom_module_files,
                                allow_destroy: true,
                                reject_if: ->(att) { att['file'].blank? }

  # Validations
  validates :name, presence: true, uniqueness: { scope: :site }

  # Aliases
  alias :scan_protocol_matchers :matchers

  # Scopes
  # - protocols matching as a subset of header
  scope :matching, ->(header) { where(id: (select { |sp| sp.matches?(header) }.collect(&:id))) }

  # - order by protocol key count
  scope :most_specific, -> { left_joins(:matchers)
                            .group(:id)
                            .order('COUNT(scan_protocol_matchers.id) DESC') }

  def matches?(header)
    matchers.all? do |spm|
      (header.key?(spm.key) && spm.matches?(header[spm.key]))
    end
  end
end

app/controllers/scan_protocols_controller.rb
class ScanProtocolsController < ApplicationController
  before_action :set_site, only: [:new, :create]
  before_action :set_scan_protocol, only: [:show, :edit, :update, :destroy, :delete_analysis_options_file, :delete_specifications_file]

  # GET /scan_protocols
  # GET /scan_protocols.json
  def index
    @scan_protocols = current_account.scan_protocols.all
  end

  # GET /scan_protocols/1
  # GET /scan_protocols/1.json
  def show
  end

  # GET /scan_protocols/new
  def new
    @scan_protocol = (@site.blank? ? ScanProtocol : @site.scan_protocols).new
    if params[:qa_session_file_id]
      @qa_session_file = current_account.qa_session_files.find(params[:qa_session_file_id])
      @scan_protocol.name = "#{@qa_session_file.scan_series} -- [GENERATED]"
      @scan_protocol.matchers << @qa_session_file.matchers
    end
  end

  # GET /scan_protocols/1/edit
  def edit
  end

  # POST /scan_protocols
  # POST /scan_protocols.json
  def create
    @scan_protocol = (@site.blank? ? ScanProtocol : @site.scan_protocols).new(scan_protocol_params)

    respond_to do |format|
      if @scan_protocol.save
        format.html { redirect_to @scan_protocol, notice: 'Scan protocol was successfully created.' }
        format.json { render :show, status: :created, location: @scan_protocol }
      else
        format.html { render :new }
        format.json { render json: @scan_protocol.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scan_protocols/1
  # PATCH/PUT /scan_protocols/1.json
  def update
    respond_to do |format|
      if @scan_protocol.update(scan_protocol_params)
        format.html { redirect_to @scan_protocol, notice: 'Scan protocol was successfully updated.' }
        format.json { render :show, status: :ok, location: @scan_protocol }
      else
        format.html { render :edit }
        format.json { render json: @scan_protocol.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scan_protocols/1
  # DELETE /scan_protocols/1.json
  def destroy
    @scan_protocol.destroy
    respond_to do |format|
      format.html { redirect_to scan_protocols_url, notice: 'Scan protocol was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def delete_specifications_file
    respond_to do |format|
      if @scan_protocol.update(specifications_file: nil)
        format.html { redirect_to @scan_protocol, notice: 'Scan protocol was successfully updated.' }
        format.json { render :show, status: :ok, location: @scan_protocol }
      else
        format.html { render :edit }
        format.json { render json: @scan_protocol.errors, status: :unprocessable_entity }
      end
    end
  end

  def delete_analysis_options_file
    respond_to do |format|
      if @scan_protocol.update(analysis_options_file: nil)
        format.html { redirect_to @scan_protocol, notice: 'Scan protocol was successfully updated.' }
        format.json { render :show, status: :ok, location: @scan_protocol }
      else
        format.html { render :edit }
        format.json { render json: @scan_protocol.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_site
      @site = current_account.sites.find(params[:site_id]) if params[:site_id]
    end

    def set_scan_protocol
      @scan_protocol = current_account.scan_protocols.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def scan_protocol_params
      params.require(:scan_protocol).permit(:site_id, :name,
        :analysis_options_file,
        :specifications_file,
        phantom_module_files_attributes: [:id, :file, :_destroy],
        matchers_attributes: [:id, :scan_header_tag_id,
          :value_type_matcher_id, :value, :matcher, :_destroy])
    end
end

app/helpers/scan_protocols_helper.rb
module ScanProtocolsHelper
end

app/views/scan_protocols/_form.html.erb
<%= form_with(model: [@site, scan_protocol], local: true, html: { class: 'form-horizontal' }) do |form| %>

<% if scan_protocol.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(scan_protocol.errors.count, "error") %> prohibited this scan_protocol from being saved:</h2>

  <ul>
    <% scan_protocol.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<hr/>

<fieldset>
  <div class="form-group">
    <%= form.label :name, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= form.text_field :name, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= form.label :site_id, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= form.collection_select :site_id, current_account.sites.all, :id, :name, {}, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= form.label :analysis_options_file, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= form.file_field :analysis_options_file %><% if scan_protocol.try(:analysis_options_file) %><span><%= scan_protocol.analysis_options_file.original_filename %></span><% end %>
    </div>
  </div>
  <div class="form-group">
    <%= form.label :specifications_file, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= form.file_field :specifications_file %><% if scan_protocol.try(:specifications_file) %><span><%= scan_protocol.specifications_file.original_filename %></span><% end %>
    </div>
  </div>
</fieldset>

<hr/>

<fieldset>
  <div class="form-group">
    <%= form.label :phantom_module_files, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= form.fields_for :phantom_module_files do |builder| %>
        <%= render 'phantom_module_file_fields', f: builder %>
      <% end %>
      <div class="links">
      <%= link_to_add_association form, :phantom_module_files, class: 'btn btn-primary btn-xs' do %>
        <i class="fa fa-plus"></i> Add phantom module file
      <% end %>
    </div>
  </div>
</fieldset>

<hr/>

<fieldset>
  <div class="form-group">
    <%= form.label :matchers, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= form.fields_for :matchers do |builder| %>
        <%= render 'matcher_fields', f: builder %>
      <% end %>
      <div class="links">
      <%= link_to_add_association form, :matchers, class: 'btn btn-primary btn-xs' do %>
        <i class="fa fa-plus"></i> Add matcher
      <% end %>
    </div>
  </div>
</fieldset>

<fieldset>
  <hr/>
  <div class="form-group">
    <div class="col-sm-12 text-right">
      <%= link_to 'Cancel', :back, class: 'btn btn-default' %>
      <%= form.submit class: 'btn btn-primary' %>
    </div>
  </div>
</fieldset>
<% end %>

app/views/scan_protocols/_matcher_fields.html.erb
<div class="nested-fields row" style="padding-left: 10px; padding-right: 20px; padding-bottom: 10px">
  <%= f.hidden_field :id %>
  <div class="col-xs-4">
    <%= f.collection_select :scan_header_tag_id, ScanHeaderTag.order(label: :asc), :id, :label, {}, class: 'form-control col-xs-4' %>
  </div>
  <!-- <div class="col-xs-4">
    <%= f.grouped_collection_select :value_type_matcher_id, ScanHeaderTag.all, :value_type_matchers, :label, :id, :label, {}, class: 'form-control', id: :value_type_matcher_id %>
  </div> -->
  <!-- <div class="col-xs-3">
    <%= f.text_field :value, class: 'form-control text-fixed-width col-xs-4' %>
  </div> -->
  <div class="col-xs-7">
    <%= f.text_field :matcher, class: 'form-control text-fixed-width' %>
  </div>
  <div class="col-xs-1">
    <%= link_to_remove_association f, class: 'btn btn-danger btn-xs' do %>
      <i class="fa fa-times"></i>
    <% end %>
  </div>
</div>

app/views/scan_protocols/_phantom_module_file_fields.html.erb
<div class="nested-fields row" style="padding-left: 10px; padding-right: 20px; padding-bottom: 10px">
  <%= f.hidden_field :id %>
  <div class="col-xs-4">
    <%= f.file_field :file %>
  </div>
</div>

app/views/scan_protocols/edit.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
  <div class="col-sm-12">
    <h2>Edit Scan Protocol</h2>
    <ol class="breadcrumb">
      <li>
        <%= link_to 'Scan Protocols', scan_protocols_path %>
      </li>
      <li class="active">
        <%= link_to @scan_protocol.id, @scan_protocol %>
      </li>
    </ol>
  </div>
</div>

<div class="wrapper wrapper-content">
  <div class="row">
    <div class="col-lg-12">
      <div class="ibox">
        <div class="ibox-title">
          <h5>Edit Scan Protocol</h5>
        </div>
        <div class="ibox-content">
          <%= render 'form', scan_protocol: @scan_protocol %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/scan_protocols/index.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
  <div class="col-sm-6">
    <h2>Scan Protocols</h2>
    <ol class="breadcrumb">
      <li class="active">
        <strong>Scan Protocols</strong>
      </li>
    </ol>
  </div>
  <div class="col-sm-6">
    <div class="title-action">
      <%= link_to new_scan_protocol_path, class: 'btn btn-primary' do %>
        <i class="fa fa-plus"></i> Scan Protocol
      <% end %>
    </div>
  </div>
</div>

<div class="wrapper wrapper-content">
  <div class="row">
    <div class="col-sm-12">
      <div class="ibox">
        <div class="ibox-title">
          <h5>Scan Protocols</h5>
        </div>
        <div class="ibox-content">
          <div class="table-responsive">
            <table class="table table-hover table-fixed">
              <thead>
                <tr>
                  <th>Name</th>
                  <th>Site</th>
                  <th>Matchers</th>
                  <th>Matched Files</th>
                </tr>
              </thead>

              <tbody>
                <% @scan_protocols.each do |scan_protocol| %>
                <tr>
                  <td><%= link_to scan_protocol, scan_protocol %></td>
                  <td><%= link_to scan_protocol.site, scan_protocol.site %></td>
                  <td>
                    <%= scan_protocol.matchers.count %>
                  </td>
                  <td><%= scan_protocol.qa_session_files.count %></td>
                  <td class="project-actions">
                    <%= link_to edit_scan_protocol_path(scan_protocol), class: 'btn btn-white btn-xs' do %>
                    <i class="fa fa-pencil"></i>
                    <% end %>
                    <%= link_to scan_protocol, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-xs' do %>
                    <i class="fa fa-times"></i>
                    <% end %>
                  </td>
                </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/scan_protocols/new.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
  <div class="col-sm-12">
    <h2>Create Scan Protocol</h2>
    <ol class="breadcrumb">
      <li>
        <%= link_to 'Scan Protocols', scan_protocols_path %>
      </li>
      <li class="active">
        <strong>New</strong>
      </li>
    </ol>
  </div>
</div>

<div class="wrapper wrapper-content">
  <div class="row">
    <div class="col-lg-12">
      <div class="ibox">
        <div class="ibox-title">
          <h5>Create Scan Protocol</h5>
        </div>
        <div class="ibox-content">
          <%= render 'form', scan_protocol: @scan_protocol %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/scan_protocols/show.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
  <div class="col-sm-6">
    <h2><%= @scan_protocol %></h2>
    <ol class="breadcrumb">
      <li>
        <%= link_to 'Scan Protocols', scan_protocols_path %>
      </li>
      <li class="active">
        <strong><%= @scan_protocol %></strong>
      </li>
    </ol>
  </div>
  <div class="col-sm-6">
    <div class="title-action">
      <%= link_to edit_scan_protocol_path(@scan_protocol), class: 'btn btn-primary btn' do %>
      <i class="fa fa-pencil"></i> Edit
      <% end %>
    </div>
  </div>
</div>

<div class="wrapper wrapper-content">
  <div class="row">
    <div class="col-lg-12">
      <div class="ibox float-e-margins">
        <div class="ibox-title">
          <h5>Scan Protocol Details</h5>
        </div>
        <div class="ibox-content">
          <dl class="dl-horizontal">
            <dt>Name</dt>
            <dd><%= @scan_protocol.name %></dd>
            <dt>Matched Files</dt>
            <dd><%= @scan_protocol.qa_session_files.count %></dd>
            <dt>Analysis Options File</dt>
            <% if @scan_protocol.analysis_options_file %>
              <dd><%= link_to @scan_protocol.analysis_options_file.original_filename, @scan_protocol.analysis_options_file_url, download: @scan_protocol.analysis_options_file.original_filename, target: '_blank' %>
              (<%= link_to delete_analysis_options_file_scan_protocol_path(@scan_protocol), method: :post, data: { confirm: 'Are you sure?' }, class: 'text-danger' do %>remove<% end %>)
              </dd>
            <% else %>
              <dd>not available</dd>
            <% end %>
            <dt>Specifications File</dt>
            <% if @scan_protocol.specifications_file %>
              <dd><%= link_to @scan_protocol.specifications_file.original_filename, @scan_protocol.specifications_file_url, download: @scan_protocol.specifications_file.original_filename, target: '_blank' %>
                (<%= link_to delete_specifications_file_scan_protocol_path(@scan_protocol), method: :post, data: { confirm: 'Are you sure?' }, class: 'text-danger' do %>remove<% end %>)
              </dd>
            <% else %>
              <dd>not available</dd>
            <% end %>
          </dl>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-12">
      <div class="ibox">
        <div class="ibox-title">
          <h5>Phantom Module Files</h5>
        </div>
        <div class="ibox-content">
          <div class="table-responsive">
            <% if @scan_protocol.phantom_module_files.count > 0 %>
              <table class="table table-hover">
                <thead>
                  <tr>
                    <th>Filename</th>
                    <th>Actions</th>
                  </tr>
                </thead>
                <tbody>
                  <% @scan_protocol.phantom_module_files.each do |pmf| %>
                  <tr>
                    <td><%= link_to pmf.file.original_filename, pmf.file.url, download: pmf.file.original_filename, target: '_blank', disposition: 'attachment' %></td>
                    <td>
                      <%= link_to pmf, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-xs' do %><i class="fa fa-times"></i><% end %>
                    </td>
                  </tr>
                  <% end %>
                </tbody>
              </table>
            <% else %>
              <p>no module files found</p>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-12">
      <div class="ibox">
        <div class="ibox-title">
          <h5>Protocol Matchers</h5>
        </div>
        <div class="ibox-content">
          <div class="table-responsive">
            <table class="table table-hover">
              <thead>
                <tr>
                  <th>Scan Header Tag</th>
                  <th>Matcher</th>
                  <th>Actions</th>
                </tr>
              </thead>
              <tbody>
                <% @scan_protocol.matchers.by_header_tag.decorate.each do |matcher| %>
                <tr>
                  <td class="text-fixed-width"><%= matcher.scan_header_tag %></td>
                  <td class="text-fixed-width"><%= matcher.matcher %></td>
                  <td>
                    <%= link_to edit_scan_protocol_matcher_path(matcher), class: 'btn btn-white btn-xs' do %><i class="fa fa-pencil"></i><% end %>
                    <%= link_to matcher, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-xs' do %><i class="fa fa-times"></i><% end %>
                  </td>
                </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>