config/routes.rb
Rails.application.routes.draw do

  resources :scan_header_tags
  resources :mime_types
  require 'sidekiq/web'

  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }
  mount Shrine.presign_endpoint(:cache) => "/qa_session_files/presign", as: 'presign_qa_session_files'

  mount Shrine.download_endpoint => "/files"

  resources :analysis_responses
  resources :analyses do
    resources :analysis_requests, shallow: true
  end
  resources :scan_protocols do
    resources :scan_protocol_matchers, shallow: true
    member do
      post :delete_specifications_file
      post :delete_analysis_options_file
    end
  end
  resources :sites do
    resources :scan_protocols, shallow: true
  end

  resources :analysis_requests do
    resources :analysis_responses, shallow: true
  end

  resources :qa_sessions do
    member do
      get :download_files
      post :match_scan_protocols
    end
    resources :qa_session_files, shallow: true
    resources :analysis_sessions, shallow: true
  end

  resources :phantom_module_files

  resources :equipment
  resources :accounts
  resources :reports

  resources :scan_series do
    member do
      get :download_files
    end
  end

  namespace :api, :defaults => { :format => :json } do
    namespace :v1 do
      resources :accounts, only: [:index, :show]
      resources :auth, only: [:create], controller: "authentication"
      resources :analysis_requests do
        resource :analysis_responses, shallow: true
      end
    end
  end

  root to: 'qa_sessions#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/scan_series_controller.rb
class ScanSeriesController < ApplicationController
  # enable streaming responses
  include ActionController::Streaming
  # enable zipline
  include Zipline

  before_action :set_scan_series, only: [:show, :edit, :update, :destroy, :download_files]

  # GET /scan_series
  # GET /scan_series.json
  def index
    @scan_series = ScanSeries.all
  end

  # GET /scan_series/1
  # GET /scan_series/1.json
  def show
  end

  # GET /scan_series/1/edit
  def edit
    session[:previous_url] = request.referrer
  end

  # PATCH/PUT /scan_series/1
  # PATCH/PUT /scan_series/1.json
  def update
    respond_to do |format|
      if @scan_series.update(scan_series_params)
        format.html { redirect_back fallback_location: session[:previous_url], notice: 'Scan series was successfully updated.' }
        format.json { render :show, status: :ok, location: @scan_series }
      else
        format.html { render :edit }
        format.json { render json: @scan_series.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scan_series/1
  # DELETE /scan_series/1.json
  def destroy
    @scan_series.destroy
    respond_to do |format|
      format.html { redirect_back fallback_location: scan_series_index_url, notice: 'Scan series was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # GET /scan_series/1/download_files
  def download_files
    files = @scan_series.qa_session_files.map { |f| [f.file, f.filename] }
    zipline(files, "#{@scan_series.description}.zip")
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_scan_series
      @scan_series = ScanSeries.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def scan_series_params
      params.require(:scan_series).permit(:key)
    end
end

app/helpers/scan_series_helper.rb
module ScanSeriesHelper
end

app/views/scan_series/_form.html.erb
<%= form_with(model: scan_series, local: true, html: { class: 'form-horizontal' }) do |form| %>
  <% if scan_series.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(scan_series.errors.count, "error") %> prohibited this scan_series from being saved:</h2>
      <ul>
      <% scan_series.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :equipment_id, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= form.collection_select :equipment_id, current_account.equipment.all, :id, :name, { prompt: "Select equipment" }, { class: 'form-control' } %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-4 col-sm-offset-2">
      <%= form.submit class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/scan_series/_scan_series.html.erb
<table class="table table-hover sortable">
  <thead>
    <th class="sorttable_nosort">Preview</th>
    <th>Status</th>
    <th>Series Description</th>
    <th>Scan Protocol</th>
    <th class="sorttable_nosort">MR Scanner</th>
    <th>File count</th>
    <th style="text-align: right" class="sorttable_nosort">Actions</th>
  </thead>
  <tbody>
    <% scan_series.each do |series| %>
      <tr>
        <td>
          <% if series.previewable? %>
            <%= image_tag series.preview.file_url(:tiny), width: "64px", height: "64px" %>
          <% else %>
            n/a
          <% end %>
        </td>
        <td>
          <% if series.report %>
            <%= link_to 'View report', report_path(series.report) %>
          <% else %>
            <%= series.status %>
          <% end %>
        </td>
        <td><%= link_to series.description, series %></td>
        <td><%= link_to series.scan_protocol, series.scan_protocol %></td>
        <td>
          <% if !series.finalized? && current_account.equipment.count > 1 %>
            <%= form_for series do |f| %>
              <%= f.collection_select(:equipment_id, current_account.equipment.all, :id, :name, {prompt:"Unassigned", class: 'form-control' }, :onchange => 'this.form.submit()') %>
            <% end %>
          <% else %>
            <%= link_to series.equipment, series.equipment %>
          <% end %>
        </td>
        <td><%= series.files.count %></td>
        <td>
          <div class="dropdown pull-right">
            <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
              <i class="fa fa-cog"></i>
              <span class="caret"></span>
            </button>
            <ul class="dropdown-menu dropdown-menu-right" aria-labelledby="dLabel">
              <!--<% unless series.finalized? %>
                <li>
                  <%= link_to 'Assign Equipment', edit_scan_series_path(series) %>
                </li>
              <% end %>-->
              <li><%= link_to 'Create Protocol', new_scan_protocol_path(qa_session_file_id: series.files.first.id) %></li>
              <li><%= link_to 'Download Files', download_files_scan_series_path(series), download: "#{series.description}.zip"%></li>
              <% unless series.finalized? %>
                <li role="separator" class="divider"></li>
                <li>
                  <%= link_to 'Delete Series', series, method: :delete, data: { confirm: 'Are you sure?' } %>
                </li>
              <% end %>
            </ul>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/scan_series/edit.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
  <div class="col-sm-12">
    <h2><%= @scan_series %></h2>
    <ol class="breadcrumb">
      <li>
        <%= link_to 'scan_series', scan_series_index_path %>
      </li>
      <li>
        <%= link_to @scan_series, @scan_series %>
      </li>
      <li>
        <strong>Edit</strong>
      </li>
    </ol>
  </div>
</div>

<div class="wrapper wrapper-content">
  <div class="row">
    <div class="col-lg-12">
      <div class="ibox">
        <div class="ibox-title">
          <h5>Edit scan_series</h5>
        </div>
        <div class="ibox-content">
          <%= render 'form', scan_series: @scan_series %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/scan_series/index.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
  <div class="col-sm-12">
    <h2>Scan Series</h2>
    <ol class="breadcrumb">
      <li class="active">
        <strong>Scan Series</strong>
      </li>
    </ol>
  </div>
</div>

<div class="wrapper wrapper-content">
  <div class="row">
    <div class="col-lg-12">
      <div class="ibox">
        <div class="ibox-title">
          <h5>Scan Series</h5>
        </div>
        <div class="ibox-content">
          <% if @scan_series.count > 0 %>
            <%= render 'scan_series/scan_series', scan_series: @scan_series %>
          <% else %>
            <p>No scan series found.</p>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/scan_series/show.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
  <div class="col-sm-12">
    <h2><%= @scan_series %></h2>
    <ol class="breadcrumb">
      <li>
        <%= link_to 'Scan Series', scan_series_index_path %>
      </li>
      <li class="active">
        <strong><%= @scan_series %></strong>
      </li>
    </ol>
  </div>
</div>

<div class="wrapper wrapper-content">
  <div class="row">
    <div class="col-lg-12">
      <div class="ibox float-e-margins">
        <div class="ibox-title">
          <h5>Scan Series Details</h5>
        </div>
        <div class="ibox-content">
          <dl class="dl-horizontal">
            <dt>UID</dt>
            <dd><%= @scan_series.uid %></dd>
            <dt>Number</dt>
            <dd><%= @scan_series.number %></dd>
            <dt>Description</dt>
            <dd><%= @scan_series.description %></dd>
          </dl>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-12">
      <div class="ibox">
        <div class="ibox-title">
          <h5>Files (<%= @scan_series.qa_session_files.count %>)</h5>
        </div>
        <div class="ibox-content">
          <%= render 'qa_session_files/qa_session_files', qa_session_files: @scan_series.qa_session_files %>
        </div>
      </div>
    </div>
  </div>
</div>