config/routes.rb
Rails.application.routes.draw do

  resources :scan_header_tags
  resources :mime_types
  require 'sidekiq/web'

  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }
  mount Shrine.presign_endpoint(:cache) => "/qa_session_files/presign", as: 'presign_qa_session_files'

  mount Shrine.download_endpoint => "/files"

  resources :analysis_responses
  resources :analyses do
    resources :analysis_requests, shallow: true
  end
  resources :scan_protocols do
    resources :scan_protocol_matchers, shallow: true
    member do
      post :delete_specifications_file
      post :delete_analysis_options_file
    end
  end
  resources :sites do
    resources :scan_protocols, shallow: true
  end

  resources :analysis_requests do
    resources :analysis_responses, shallow: true
  end

  resources :qa_sessions do
    member do
      get :download_files
      post :match_scan_protocols
    end
    resources :qa_session_files, shallow: true
    resources :analysis_sessions, shallow: true
  end

  resources :phantom_module_files

  resources :equipment
  resources :accounts
  resources :reports

  resources :scan_series do
    member do
      get :download_files
    end
  end

  namespace :api, :defaults => { :format => :json } do
    namespace :v1 do
      resources :accounts, only: [:index, :show]
      resources :auth, only: [:create], controller: "authentication"
      resources :analysis_requests do
        resource :analysis_responses, shallow: true
      end
    end
  end

  root to: 'qa_sessions#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/qa_session.rb
class QaSession < ApplicationRecord
  include Keyable

  # Relationships
  belongs_to :account
  has_many :scan_series, dependent: :destroy
  has_many :qa_session_files, dependent: :destroy
  has_many :scan_protocols, through: :qa_session_files
  has_many :analysis_sessions, dependent: :destroy

  before_save :set_default_values

  delegate :equipment, to: :account

  def analyzed_file_count
    qa_session_files.select { |f| f.scan_attributes_extracted }.count
  end

  def analyzed_file_ratio
    return 0 if qa_session_files.count == 0
    ((analyzed_file_count.to_f / qa_session_files.count) * 100).to_i
  end

  def set_default_values
    self.performed_at ||= Time.now
  end

  def self.unfinalized
    where(id: select { |s| s.analysis_sessions.count == 0 }.collect(&:id))
  end
end

app/controllers/qa_sessions_controller.rb
class QaSessionsController < ApplicationController
  # enable streaming responses
  include ActionController::Streaming
  # enable zipline
  include Zipline

  before_action :set_qa_session, only: [:show, :edit, :update, :destroy, :download_files, :match_scan_protocols]
  before_action :redirect_to_unfinalized, only: [:new, :create]

  # GET /qa_sessions
  # GET /qa_sessions.json
  def index
    @qa_sessions = current_account.qa_sessions.all.order(performed_at: :desc)
  end

  # GET /qa_sessions/1
  # GET /qa_sessions/1.json
  def show
  end

  # GET /qa_sessions/new
  def new
    @qa_session = current_account.qa_sessions.new
    @qa_session.performed_at = Time.now.to_date.to_s(:db)
  end

  # GET /qa_sessions/1/edit
  def edit
  end

  # POST /qa_sessions
  # POST /qa_sessions.json
  def create
    @qa_session = current_account.qa_sessions.new
    @qa_session.assign_attributes(qa_session_params)

    respond_to do |format|
      if @qa_session.save
        format.html { redirect_to @qa_session, notice: 'QA session was successfully created.' }
        format.json { render :show, status: :created, location: @qa_session }
      else
        format.html { render :new }
        format.json { render json: @qa_session.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /qa_sessions/1
  # PATCH/PUT /qa_sessions/1.json
  def update
    respond_to do |format|
      if @qa_session.update(qa_session_params)
        format.html { redirect_to @qa_session, notice: 'QA session was successfully updated.' }
        format.json { render :show, status: :ok, location: @qa_session }
      else
        format.html { render :edit }
        format.json { render json: @qa_session.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /qa_sessions/1
  # DELETE /qa_sessions/1.json
  def destroy
    @qa_session.destroy
    respond_to do |format|
      format.html { redirect_to qa_sessions_url, notice: 'QA session was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # POST /qa_sessions/1/match_scan_protocols
  def match_scan_protocols
    @qa_session.qa_session_files.each { |f| f.match_scan_protocol(force: true); f.save }
    redirect_to @qa_session, notice: 'qa_session files successfully re-analyzed.'
  end

  # GET /qa_sessions/1/download_files
  def download_files
    files = @qa_session.qa_session_files.map { |f| [f.file, f.original_filename] }
    zipline(files, "#{@qa_session.key}.zip")
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_qa_session
      @qa_session = current_account.qa_sessions.friendly.find(params[:id])
    end

    def set_equipment
      @equipment = current_account.equipment.find(params[:equipment_id]) if params[:equipment_id]
    end

    def redirect_to_unfinalized
      @qa_session = current_account.qa_sessions.unfinalized.first
      unless @qa_session.blank?
        respond_to do |format|
          format.html { redirect_to @qa_session }
          format.json { render :show, status: :ok, location: @qa_session }
        end
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def qa_session_params
      params.fetch(:qa_session, {}).permit(:equipment_id, :performed_at)
    end
end

app/helpers/qa_session_helper.rb
module QaSessionHelper
end

app/views/qa_sessions/_form.html.erb
<%= form_with(model: qa_session, local: true, html: { class: 'form-horizontal' }) do |form| %>
<% if qa_session.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(qa_session.errors.count, "error") %> prohibited this qa_session from being saved:</h2>

  <ul>
    <% qa_session.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="form-group">
  <%= form.label :equipment_id, class: 'col-sm-2 control-label' %>
  <div class="col-sm-10">
    <%= form.collection_select :equipment_id, Equipment.all, :id, :name, { prompt: "Select equipment" }, { class: 'form-control' } %>
  </div>
</div>

<!-- <div class="form-group">
  <%= form.label :performed_at, class: 'col-sm-2 control-label' %>
  <div class="col-sm-10">
    <div class="input-group date">
      <%= form.text_field :performed_at, class: 'datepicker form-control' %>
    </div>
  </div>
</div> -->

<div class="form-group">
  <div class="col-sm-4 col-sm-offset-2">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
</div>
<% end %>

app/views/qa_sessions/_qa_sessions.html.erb
<% if qa_sessions && qa_sessions.count > 0 %>
<div class="table-responsive">
  <table class="table table-hover issue-tracker">
    <thead>
      <tr>
        <th>Status</th>
        <th>Nr.</th>
        <th>Subject</th>
        <th>Created at</th>
        <th>Created by</th>
        <th>Files</th>
      </tr>
    </thead>
    <tbody>
      <% qa_sessions.order(created_at: :desc).decorate.each do |qa_session| %>
      <tr>
        <td>
          <% if qa_session.analysis_sessions.count > 0 %>
            <span class="label label-success">Finalized</span>
          <% else %>
            <span class="label label-warning">Unfinalized</span>
          <% end %>
        </td>
        <td>
          <%= link_to qa_session.friendly_name, qa_session %>
        </td>
        <td>
          TODO
        </td>
        <td>
          <%= qa_session.created_at %>
        </td>
        <td>
          Bjarki
        </td>
        <td>
          <%= qa_session.qa_session_files.count %>
        </td>
        <td class="project-actions">
          <% if qa_session.analysis_sessions.empty? %>
            <%= link_to qa_session, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-xs' do %>
            <i class="fa fa-times"></i>
            <% end %>
          <% end %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>
<% else %>
<div>
  <p>No qa_sessions yet.</p>
</div>
<% end %>

app/views/qa_sessions/edit.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
  <div class="col-sm-12">
    <h2><%= @qa_session %></h2>
    <ol class="breadcrumb">
      <li>
        <%= link_to 'qa_sessions', qa_sessions_path %>
      </li>
      <li>
        <%= link_to @qa_session, @qa_session %>
      </li>
      <li>
        <strong>Edit</strong>
      </li>
    </ol>
  </div>
</div>

<div class="wrapper wrapper-content">
  <div class="row">
    <div class="col-lg-12">
      <div class="ibox">
        <div class="ibox-title">
          <h5>Edit qa_session</h5>
        </div>
        <div class="ibox-content">
          <%= render 'form', qa_session: @qa_session %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/qa_sessions/index.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
  <div class="col-sm-6">
    <h2>QA Sessions</h2>
    <ol class="breadcrumb">
      <li class="active">
        <strong>QA Sessions</strong>
      </li>
    </ol>
  </div>
  <div class="col-sm-6">
    <div class="title-action">
      <%= link_to qa_sessions_path, class: 'btn btn-primary', method: :post do %>
      <i class="fa fa-play-circle"></i> Upload
      <% end %>
    </div>
  </div>
</div>

<div class="wrapper wrapper-content">
  <div class="row">
    <div class="col-lg-12">
      <% if current_account.qa_sessions.count > 0 %>
      <div class="ibox">
        <div class="ibox-title">
          <h5>QA Sessions</h5>
        </div>
        <div class="ibox-content">
          <%= render 'qa_sessions/qa_sessions', qa_sessions: @qa_sessions %>
        </div>
      </div>
      <% else %>
      <div class="ibox">
        <div class="ibox-title">
          <h5>QA Sessions</h5>
        </div>
        <div class="ibox-content">
          <p>You have no QA sessions.</p>
          <%= link_to qa_sessions_path, class: 'btn btn-primary', method: :post do %>
            <i class="fa fa-play-circle"></i> Upload
          <% end %>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/qa_sessions/new.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
  <div class="col-sm-12">
    <h2>Create qa_session</h2>
    <ol class="breadcrumb">
      <li>
        <%= link_to 'QaSessions', qa_sessions_path %>
      </li>
      <li class="active">
        <strong>New</strong>
      </li>
    </ol>
  </div>
</div>

<div class="wrapper wrapper-content">
  <div class="row">
    <div class="col-lg-12">
      <div class="ibox">
        <div class="ibox-title">
          <h5>New qa_session</h5>
        </div>
        <div class="ibox-content">
          <%= render 'form', qa_session: @qa_session %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/qa_sessions/show.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
  <div class="col-sm-12">
    <h2>QA Session at <%= @qa_session.created_at.to_s(:db) %></h2>
    <ol class="breadcrumb">
      <li>
        <%= link_to 'QA Sessions', qa_sessions_path %>
      </li>
      <li class="active">
        <strong><%= @qa_session.created_at.to_s(:db) %></strong>
      </li>
    </ol>
  </div>
</div>

<div class="wrapper wrapper-content">
  <% if @qa_session.analysis_sessions.count > 0 %>
    <div class="row">
      <div class="col-lg-12">
        <div class="ibox">
          <div class="ibox-title">
            <p>This QA session has been finalized please see <%= link_to "reports", reports_path %> for further details.</p>
          </div>
        </div>
      </div>
    </div>
  <% else %>
    <div class="row">
      <div class="col-lg-12">
        <div class="ibox">
          <div class="ibox-title">
            <h5>Files</h5>
          </div>
          <div class="ibox-content">
            <form action="#">
              <input type="file" multiple="" data-presign-path="<%= presign_qa_session_files_path(format: :json) %>" data-success-path="<%= qa_session_qa_session_files_path(@qa_session, format: :json) %>" } %>
            </form>
          </div>
        </div>
      </div>
    </div>
  <% end %>

  <div class="row">
    <div class="col-lg-12">
      <div class="ibox">
        <div class="ibox-title">
          <h5>Scan Series</h5>
        </div>
        <div class="ibox-content">
          <% if @qa_session.qa_session_files.empty? %>
            No files uploaded yet.
          <% elsif @qa_session.qa_session_files.all? { |f| f.scan_attributes_extracted } %>
            <%= render 'scan_series/scan_series', scan_series: @qa_session.scan_series.uniq %>
          <% else %>
            <div class="progress">
              <div style="width: <%= @qa_session.analyzed_file_ratio %>%;" class="progress-bar"></div>
            </div>
            <div class="m-t-sm small">
              Inspecting file headers
              <%= @qa_session.analyzed_file_count %>
              of
              <%= @qa_session.qa_session_files.count %> files. Page will refresh automatically.
            </div>
            <script>setTimeout(window.location.reload.bind(window.location), 5000);</script>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <% if @qa_session.qa_session_files.count > 0 && @qa_session.qa_session_files.all? { |f| f.scan_attributes_extracted } && @qa_session.analysis_sessions.count == 0 %>
  <div class="row">
    <div class="col-sm-12">
      <div class="ibox float-e-margins">
        <div class="ibox-title">
          <h5>Processing</h5>
        </div>
        <div class="ibox-content">
          <% if @qa_session.scan_series.all? { |ss| !!ss.equipment } %>
            <h4>Done uploading?</h4>
            <%= link_to "Start processing", qa_session_analysis_sessions_path(@qa_session), class: 'btn btn-primary btn-lg btn-block', method: :post %>
          <% else %>
            <p class="text-danger text-center">Not all series have assigned equipment.</p>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <% end %>
</div>